linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gosec
    - bodyclose
    - noctx
    - exportloopref

linters-settings:
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G104 # Duplicates errcheck

run:
  timeout: 5m
